#!usr/bin/etc python
# -.- coding: utf-8 -.-

import time
import os

#color
A='\033[31;40m'
B='\033[32;40m'
C='\033[33;40m'
E='\033[34;40m'
F='\033[35;40m'
G='\033[36;40m'
END='\033[37;40m'

#cadre-color
end='\033[40m'
a='\033[41m'
b='\033[42m'
c='\033[43m'
d='\033[44m'
e='\033[45m'
f='\033[46m'
g='\033[47m'
#--------------
os.system("clear")
os.system("clear")
os.system("clear")

#SCripTs
print (A,"a")
print ("")
print ("")
print ("")
time.sleep(0.2)
os.system("clear")
print (B,".")
print (A,"a")
print ("")
print ("")
time.sleep(0.2)
os.system("clear")
print (B,".")
print (".")
print (A,"a")
print ("")
time.sleep(0.2)
os.system("clear")
print (B,".")
print (".")
print (".")
print (A,"A")
time.sleep(0.1)
os.system("clear")
print ("")
print ("")
print ("")
print (" A")
time.sleep(0.1)
os.system("clear")
print ("")
print ("")
print ("")
print ("  A")
time.sleep(0.1)
os.system("clear")
print ("")
print ("")
print ("")
print ("   A")
time.sleep(0.1)
os.system("clear")
print ("")
print ("")
print ("")
print ("    A")
time.sleep(0.1)
os.system("clear")
print (B,"i")
print ("")
print ("")
print (A,"    A")
time.sleep(0.2)
os.system("clear")
print (B,".")
print ("i")
print (" ")
print (A,"    a ")
time.sleep(0.2)
os.system("clear")
print (C,".")
print (".")
print (B,"i")
print (A,"     A")
time.sleep(0.2)
os.system("clear")
print ("")
print ("")
print ("")
print (B,"I",A,"    A")
time.sleep(0.1)
os.system("clear")
print ("")
print ("")
print ("")
print (B," I",A,"   A")
time.sleep(0.1)
os.system("clear")
print ("")
print ("")
print ("")
print (B,"  I",A,"  A")
time.sleep(0.1)
os.system("clear")
print ("")
print ("")
print ("")
print (B,"   I A")
time.sleep(0.1)
os.system("clear")
print ("")
print ("")
print ("")
print ("    IA")
time.sleep(0.06)
os.system("clear")
print ("")
print ("")
print ("")
print ("    I   A")
time.sleep(0.06)
os.system("clear")
print ("")
print ("")
print ("")
print ("    I       A")
time.sleep(0.06)
os.system("clear")
print ("")
print ("")
print ("")
print ("    I   A")
time.sleep(0.06)
os.system("clear")
print (C,"h")
print ("")
print ("")
print (B,"    IA")
time.sleep(0.2)
os.system("clear")
print (F,".")
print (C,"h")
print ("")
print (B,"    IA")
time.sleep(0.2)
os.system("clear")
print (F,".")
print (".")
print (C,"h")
print (B,"    IA")
time.sleep(0.2)
os.system("clear")
print (F,".")
print (".")
print (".")
print (C,"H ",B,"  IA")
time.sleep(0.1)
os.system("clear")
print ("")
print ("")
print ("")
print (C," H",B,"  IA")
time.sleep(0.1)
os.system("clear")
print ("")
print ("")
print ("")
print (C,"  H IA")
time.sleep(0.1)
os.system("clear")
print ("")
print ("")
print ("")
print ("  HI    A")
time.sleep(0.06)
os.system("clear")
print ("")
print ("")
print ("")
print ("  HI        A")
time.sleep(0.06)
os.system("clear")
print ("")
print ("")
print ("")
print ("  HI                A")
time.sleep(0.06)
os.system("clear")
print ("")
print ("")
print ("")
print ("  HI       A")
time.sleep(0.06)
os.system("clear")
print ("")
print ("")
print ("")
print ("  HI   A")
time.sleep(0.06)
os.system("clear")
print (F,"e")
print ("")
print ("")
print (B,"  HIA")
time.sleep(0.2)
os.system("clear")
print (G,".")
print (F,"e")
print ("")
print (C,"  HIA")
time.sleep(0.2)
os.system("clear")
print (G,".")
print (".")
print (F,"e")
print (C,"  HIA")
time.sleep(0.2)
os.system("clear")
print (G,".")
print (".")
print (".")
print (F,"E HIA")
time.sleep(0.06)
os.system("clear")
print ("")
print ("")
print ("")
print (" EHI     A")
time.sleep(0.06)
os.system("clear")
print ("")
print ("")
print ("")
print (" EHI             A")
time.sleep(0.06)
os.system("clear")
print ("")
print ("")
print ("")
print (" EHI       A")
time.sleep(0.06)
os.system("clear")
print ("")
print ("")
print ("")
print (" EHI   A")
time.sleep(0.06)
os.system("clear")
print (G,"Y")
print ("")
print ("")
print (" EHIA")
time.sleep(0.06)
os.system("clear")
print (F,".",END)
print (G,"y")
print ("")
print (F," EHIA")
time.sleep(0.06)
os.system("clear")
print (d,".")
print (".")
print (G,"y")
print (F," EHIA")
time.sleep(0.3)
os.system("clear")
print ("")
print ("")
print (F," EHIA",END)
print ("\033[33;44mY    ",END)
time.sleep(0.3)
os.system("clear")
print ("")
print ("")
print (F,"  HIA",END)
print ("\033[33;44mYE   ",END)
time.sleep(0.3)
os.system("clear")
print ("")
print ("")
print (F,"   IA",END)
print ("\033[33;44mYEH  ",END)
time.sleep(0.3)
os.system("clear")
print ("")
print ("")
print (F,"    A")
print ("\033[33;44mYEHI ",END)
time.sleep(0.3)
os.system("clear")
print ("")
print ("")
print ("")
print ("\033[33;45mYEHIA",END)
